# Generated by Django 4.0.5 on 2022-09-12 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_category_name_alter_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='imageUrl',
            field=models.CharField(default=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_list', to='auctions.category'),
        ),
    ]
