# Generated by Django 4.0.5 on 2022-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_bid_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgUrl',
            field=models.CharField(default=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
