# Generated by Django 4.0.5 on 2022-09-21 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_remove_listing_bid_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addBid', to='auctions.bid'),
        ),
    ]
